### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by lferro9000** [xtreamwayz/xtreamwayz.com#10]
Hi Geert,

I'm using this site as a reference on how to implement a site with zend expressive / psr7 / middleware.

Fatally, some code will be very similar and i would like to avoid licensing issues if possible.

Do you mind adding license information on the project?

Cheers,
LF

**Comment by xtreamwayz** [comment]
Feel free to use the code in whatever way you want, except for the posts in https://github.com/xtreamwayz/xtreamwayz.com/tree/master/data/posts of course.

The code is under [MIT](https://github.com/xtreamwayz/xtreamwayz.com/blob/master/composer.json#L5) license. I'll add this to the readme as well.
